CREATE DATABASE IF NOT EXISTS tutorvideos
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE tutorvideos;

CREATE TABLE IF NOT EXISTS animales (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(100) NOT NULL,
    edad INT NOT NULL,
    raza VARCHAR(100) NOT NULL,
    creado_en TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
